services:
  rmq:
    image: rabbitmq:4-management-alpine
    networks:
      - app
    ports:
      - 8081:15672
      - 5672:5672
      - 25676:25676
  api:
    build:
      context: .
      dockerfile: .
    volumes:
      - .:/usr/app
    depends_on:
      - db
    networks:
      - app
    ports:
      - 3333:3000

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345678
    networks:
      - app

networks:
  app:
