services:
  api:
    build:
      context: .
      dockerfile: .
    volumes:
      - .:/usr/app
    depends_on:
      - db
    networks:
      - app
    ports:
      - 3333:3000

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345678
    networks:
      - app

networks:
  app:
