import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Player from "@/components/Player";
import { PlayerProvider } from "@/core/Context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className="" style={roboto.style}>
        <PlayerProvider>
          {children}
          <div className="w-full h-full px-2 fixed top-0">
            <Player />
          </div>
        </PlayerProvider>
      </body>
    </html>
  );
}
