[package]
name = "libflow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rodio = "0.19.0"
ureq = "2.10.1"
tokio = { version = "1.40.0", features = ["full"] }
rust_socketio = "0.6.0"
serde_json = "1.0.128"