version: '3.1'

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345678

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
